app/config/config.local.neon.sample, app/config/config.neon, app/config/router.neon, app/config/services.neon, app/model/Authentication/GithubAuthenticator.php, app/model/Authentication/LoginUserStorage.php, app/model/FullHttpRequest.php, app/model/Github/EventFactory.php, app/model/Github/Events/Event.php, app/model/Github/Events/PingEvent.php, app/model/Github/Events/PushEvent.php, app/model/Github/Repository.php, app/model/Github/User.php, app/model/Maintenance/Updater.php, app/presenters/GithubPresenter.php, app/presenters/core/AuthenticatedPresenter.php, app/presenters/core/BasePresenter.php, install.sh
=> GitHub hooks

.gitmodules
=> [git] Update tester submodule URL

app/config/config.neon
Nové cesty ke XML na Astrid. @cevro @Auratons  bude to fungovat ve Výfuku?
=> [config] task import

app/OrgModule/presenters/PointsPresenter.php, app/model/ORM/models/ModelPersonHistory.php
Now label in points submit shows also school of the contestant. Serves for distinguishing contestants with same name.
=> Enhanced label in points submit

app/model/ORM/services/Event/ServiceFyziklaniTeam.php
Found by automated test
Stay tuned for more (Werkov/fksdb, branch fof-tests)
=> [orm] ServiceFyziklaniTeam minor fix

app/model/Fyziklani/CloseSubmitStrategy.php
Fix saving rank to DB
Closes #66
=> [fof] rank saving fix

app/FyziklaniModule/presenters/SubmitPresenter.php
reišenie https://github.com/fykosak/fksdb/issues/59
=> [FOF] entry message + on error clean up input

app/FyziklaniModule/presenters/ClosePresenter.php, app/FyziklaniModule/presenters/SubmitPresenter.php
=> [fof] Simplify actions redirects

www/js/jsx/fyziklaniResults.js, www/js/jsx/fyziklaniResults.tsx
Riešenie https://github.com/fykosak/fksdb/issues/63
=> [FOF] vysledkovka fix popisov a sortovania

www/js/jsx/fyziklaniResults.js, www/js/jsx/fyziklaniResults.tsx
https://github.com/fykosak/fksdb/issues/61
=> [FOF] results container's width

app/Components/Grids/Fyziklani/FyziklaniSubmitsGrid.php, app/FyziklaniModule/presenters/ResultsPresenter.php, data/events/fyziklani/fyziklani11.neon
U paginace submitů je otázka zdali (ale z výkonnostních důvodů na straně serveru i klienta jsem pro).
=> Fof hotfixes

app/config/acl.neon, sql/initval.sql
Distinguish between internal and external export safety policy.
=> wiki-safe tag

app/config/contests.neon
Allow editing born and birthplace for organizers in GUI.
=> [orgs] add born and birthplace to form

app/Components/Forms/Factories/PersonFactory.php, tests/PublicModule/ApplicationPresenter.tsaf7-cancel.phpt, tests/PublicModule/ApplicationPresenter.tsaf7-nodsef.phpt, tests/PublicModule/ApplicationPresenter.tsaf7-withdsef.phpt, tests/PublicModule/ApplicationPresenter.tsaf7-withdsefAdmin.phpt
We want phone numbers in format \+420[01][0-9]{3}
=> Fix accepted phone format

app/model/Exports/StoredQueryFactory.php, www/FKSDBWebServices.wsdl, www/xml/export/schema.xsd, www/xml/results/schema.xsd, www/xml/series/schema.xsd, www/xml/stats/schema.xsd
=> Move XSD's to FKSDB

app/Components/Forms/Factories/PersonFactory.php, libs/Forms/DatePicker/DatePicker.php, www/js/datePicker.js
Not sure if it's OK to modify library code.
=> [UI] set sane default value for date picker

app/model/results/SchoolCumulativeResultsModel.php
=> [results] fix division by zero

app/model/ORM/services/ServiceOrg.php, app/model/ORM/services/ServicePerson.php, app/model/Tasks/ContributionsFromXML2.php, app/model/Tasks/Legacy/ContributionsFromXML.php, app/model/Tasks/PipelineFactory.php
A while ago, tex_signature was moved from person_info to org. This PR reflects the refactoring in task import code.
=> Fix adding task contribution

app/model/ORM/models/Events/ModelFyziklaniTeam.php, app/model/ORM/services/Event/ServiceFyziklaniTeam.php
fix https://github.com/fykosak/fksdb/issues/217
=> Pridanie týmov s viacerými statusmi do routingu

data/events/fyziklani.form.latte
Potreba preložiť SK-EN a skultúrniť angličtinu.
=> Ubytovanie pre FOF info

data/events/fyziklani.form.latte, data/events/fyziklani/fyziklani12.neon
=> Add hotel Duo

data/events/fyziklani.form.latte
Ak sa niekomu chce preložte to. Celkom to inak horí
=> [FOF-HORI] Informácie o naplnení B a C

app/Components/Grids/Fyziklani/FyziklaniSubmitsGrid.php
Blbý checkout z mastra, namergovať ja s brawl-lib
=> hotfix grigu

www/aesop/fykos.txt
Nekdo povolaný prosím rovnou updatujte i výfuk.
=> [aesop] update

app/model/Persons/Deduplication/DuplicateFinder.php
Bottleneck byl $person->getInfo(). Pomohlo vytažení potřebných informací z person_info left joinem v původním dotazu.
=> Optimize person duplicate finding

app/model/React/ReactMessage.php, app/model/React/ReactResponse.php, www/js/TypeScriptSources/src/fetch-api/actions/submit.ts, www/js/TypeScriptSources/src/fetch-api/middleware/fetch.ts, www/js/TypeScriptSources/src/fetch-api/middleware/interfaces.ts, www/js/TypeScriptSources/src/fetch-api/reducers/submit.ts
Kedže ten celok, čo som začal vyvíjať ako prihlasovanie na FOF je zas neuveriteľný veľký vysekol pár vecí, čo môžu isť samostatne.
Prvá vec je pokus o jednotné api na komunikáciu medzi nette a reactom.
=> React fetch api

app/Components/Controls/Stalking/Flag.latte
=> [stalking] fix flag html

app/Components/Forms/Factories/TeacherFactory.php, app/Components/Grids/BaseGrid.paginator.v4.latte, app/Components/Grids/BaseGrid.php, app/Components/Grids/BaseGrid.v4.latte, app/Components/Grids/TeachersGrid.php, app/OrgModule/presenters/TeacherPresenter.php, app/OrgModule/templates/Teacher/create.latte, app/OrgModule/templates/Teacher/edit.latte, app/OrgModule/templates/Teacher/list.latte, app/config/acl.neon, app/config/contests.neon, app/config/forms.neon, app/config/navigation.neon, app/config/orm.neon, app/model/ORM/DbNames.php, app/model/ORM/models/ModelTeacher.php, app/model/ORM/services/ServiceTeacher.php, i18n/locale/cs/LC_MESSAGES/messages.po, i18n/locale/en/LC_MESSAGES/messages.po, i18n/locale/sk/LC_MESSAGES/messages.po, sql/schema.sql
=> Pridanie učiteľov do FKSDB

app/model/SeriesCalculator.php
Zobrazovat ne předposlední (celkově) sérii, ale poslední ukončenou sérii.
=> [series] new computation of current series

data/events/soustredeni.neon
Spravte prosím na tom aj jazykové korektúry. Ďakujem
=> pridanie statusu "reší se mimo FKSDB"

app/Components/Controls/Events/ApplicationComponent.php, app/Components/Controls/Events/ImportComponent.php, app/Components/Forms/Containers/PersonContainer.php, app/Components/Forms/Factories/StoredQueryFactory.php, app/Components/Grids/BaseGrid.php, app/Components/Grids/Deduplicate/PersonsGrid.php, app/Components/Grids/EventOrgsGrid.php, app/Components/Grids/Events/EventsGrid.php, app/Components/Grids/Fyziklani/FyziklaniSubmitsGrid.php, app/Components/Grids/Fyziklani/FyziklaniTeamsGrid.php, app/Components/Grids/OrgsGrid.php, app/Components/Grids/SchoolsGrid.php, app/Components/Grids/StoredQueriesGrid.php, app/Components/Grids/SubmitsGrid.php, app/Components/Grids/TeachersGrid.php, app/OrgModule/presenters/EventPresenter.php, app/OrgModule/presenters/ExtendedPersonPresenter.php, app/OrgModule/presenters/StalkingPresenter.php, app/PublicModule/presenters/ApplicationPresenter.php, app/PublicModule/presenters/RegisterPresenter.php, app/model/Events/Spec/Fol/BornCheck.php, app/model/Events/Spec/Fol/FlagCheck.php, app/model/Events/Spec/Fyziklani/SchoolsInTeam.php, app/model/Events/Spec/Fyziklani/TeamsPerSchool.php
fixed #258 
lost php <5.4 compatibility
=> remove $that=$this

app/PublicModule/presenters/RegisterPresenter.php, app/PublicModule/templates/Register/year.latte
Fix year computaion in registration forms.
=> [register] fix forward registration

app/Components/Controls/Stalking/Address.latte, app/Components/Controls/Stalking/Address.php, app/Components/Controls/Stalking/BaseInfo.latte, app/Components/Controls/Stalking/BaseInfo.php, app/Components/Controls/Stalking/Contestant.php, app/Components/Controls/Stalking/EventOrg.php, app/Components/Controls/Stalking/EventParticipant.php, app/Components/Controls/Stalking/EventTeacher.latte, app/Components/Controls/Stalking/EventTeacher.php, app/Components/Controls/Stalking/Flag.latte, app/Components/Controls/Stalking/Flag.php, app/Components/Controls/Stalking/Login.latte, app/Components/Controls/Stalking/Login.php, app/Components/Controls/Stalking/Org.php, app/Components/Controls/Stalking/PersonHistory.latte, app/Components/Controls/Stalking/PersonHistory.php, app/Components/Controls/Stalking/Role.latte, app/Components/Controls/Stalking/Role.php, app/Components/Controls/Stalking/StalkingComponent.php, app/Components/Controls/Stalking/helpers/PermissionDenied.latte, app/Components/Controls/Stalking/helpers/PermissionDenied.php, app/OrgModule/presenters/StalkingPresenter.php, app/config/acl.neon, app/model/Authorization/ContestAuthorizator.php
Jedná sa o zmenu aj v právach teda asi budem potrebovať názor.
=> Update práv v stalkingu

app/presenters/DispatchPresenter.php, app/templates/Dispatch/default.latte
=> add register to dispatch screen

app/model/Submits/PDFStamper.php
=> Fix stamper

app/OrgModule/presenters/MailSenderPresenter.php, app/OrgModule/templates/MailSender/default.latte, app/config/acl.neon
=> add mail GUI

app/config/config.local.neon.sample
Enable Secure flag for session cookie.
=> [session] enable secure flag

app/model/ValidationTest/Tests/EventCoveringTest.php, app/model/ValidationTest/ValidationFactory.php, app/model/ValidationTest/ValidationLog.php
=> Add new test

app/config/navigation.neon, app/modules/CommonModule/presenters/BasePresenter.php, app/modules/CommonModule/templates/Dashboard/default.latte, app/modules/CommonModule/templates/Validation/default.latte, app/modules/EventModule/presenters/BasePresenter.php, app/modules/EventModule/templates/Dashboard/default.latte, app/modules/EventModule/templates/Seating/default.latte, app/modules/FyziklaniModule/presenters/BasePresenter.php, app/modules/FyziklaniModule/presenters/ResultsPresenter.php, app/modules/FyziklaniModule/templates/Dashboard/default.latte, app/modules/FyziklaniModule/templates/Results/list.latte, app/modules/OrgModule/presenters/BasePresenter.php, app/modules/OrgModule/templates/Dashboard/default.latte, app/modules/OrgModule/templates/Inbox/default.latte, app/modules/PublicModule/presenters/BasePresenter.php, app/modules/PublicModule/templates/Dashboard/default.latte
Links is in nette~2.4.0 case sensitive.
=> Update nette/di (prep. #1) -- Fix links case sensitivity

app/Config/Extensions/RouterExtension.php, app/config/router.neon
new Neon doesn't parse keys of arrays
=> Update nette/di (prep. #4) -- Router

app/Components/Controls/Events/ImportComponent.php, app/Components/Controls/StoredQueryComponent.php, app/Components/Grids/StoredQueryGrid.php, app/Components/Grids/TeachersGrid.php, app/Config/Extensions/RouterExtension.php, app/config/navigation.neon, app/model/Events/EventDispatchFactory.php, app/model/Events/Model/ImportHandler.php, app/model/Events/Spec/Sous/Heuristics.php, app/model/Events/Transitions/MailSender.php, app/model/Exports/Processings/AESOPContestant.php, app/model/Exports/StoredQueryPostProcessing.php, app/model/ORM/Models/ModelTeacher.php, app/model/ORM/Models/StoredQuery/ModelStoredQuery.php, app/model/ORM/Services/ServiceAuthToken.php, app/model/SeriesCalculator.php, app/modules/OrgModule/presenters/ExportPresenter.php, data/emails/sous/inc/urgent3.latte, data/emails/sous/invited.cs.latte, data/emails/sous/spare.cs.latte, data/events/soustredeni/sous34p.neon, libs/Nette/Config/Extensions/NetteExtension.php, libs/Utils/Utils.php, tests/Export/Formats/AESOPFormat.test.phpt
Updatom som eventy sústredka:
* premenoval som parametre deadline,
* zmenil parametre v emailoch, -- emaily niesu spätne kompatibilné.
* zmenil som predmet emailov
ďalej som fixol pár vecí:
* zabudnuté barDump-y, 
* prvá seria v ročníku, 
* nejaký zlý merge v navigacii.
* Nette\DateTime nemá `__toString()`
* lepšie natypovanie FKSDB\Events\Transitions\MailSender
* zavrhnutá heurisstika sustredenia
=> Dev soustredeni 34p

app/modules/PublicModule/presenters/SubmitPresenter.php
Hotfix - pokud neexistoval submit, formulář měl defaultně označenou poslední do formu přidanou možnost.
Approve ASAP.
=> Hotfix of quiz form

composer.json, tests/PresentersTests/PageDisplay/CoreModule.phpt, tests/PresentersTests/PageDisplay/PublicModule.phpt
=> run test parallel

app/Components/Controls/Chart/Event/SingleApplicationsTimeProgress.php, app/Components/Controls/Chart/Event/TeamApplicationsTimeProgress.php, app/Components/Controls/Stalking/layout.container.latte, app/Components/Grids/StoredQuery/StoredQueriesGrid.php, app/Modules/OrgModule/presenters/PointsPresenter.php, app/Modules/OrgModule/templates/Inbox/inbox.latte, app/Modules/PublicModule/presenters/RegisterPresenter.php, app/config/DBReflection.neon, i18n/locale/cs/LC_MESSAGES/messages.po
I've extracted .po files and add Czech translations, mainly for org module.
=> Czech translations

app/config/stalking.neon
=> fixes #939

data/emails/sous/34j.call.cs.latte, data/emails/sous/34j.call.en.latte, data/emails/sous/34j.cs.latte, data/emails/sous/34j.en.latte, data/emails/sous/inc/price.cs.latte, data/emails/sous/interested-applied.cs.latte, data/emails/sous/interested-applied.en.latte, data/emails/sous/spare-invited.cs.latte, data/emails/sous/spare-invited.en.latte, data/events/soustredeni/sous34j.neon, data/events/soustredeni/sous34p.neon, i18n/locale/cs/LC_MESSAGES/messages.po, i18n/locale/en/LC_MESSAGES/messages.po, i18n/locale/sk/LC_MESSAGES/messages.po
- emails have intentionally only Czech translation
- i18n: just two sentences
=> Soustredeni 34 jaro

app/Components/Controls/Stalking/StalkingContainer.php, app/Components/Controls/Stalking/layout.container.latte, app/Models/ORM/Models/ModelEmailMessage.php, app/config/stalking.neon, sql/schema.sql, tools/mailer.php
=> Email message add person_id

data/events/soustredeni/soustredeni.neon
This reverts commit d3628a49462d5a60e13959a9e28587fe50b69f05.
=> Revert "Remove unnecessary parameters"

data/events/dsef/dsef27.neon
=> Delete DSEF Accommodation

data/events/fol/fol11.neon, i18n/locale/cs/LC_MESSAGES/messages.po, i18n/locale/en/LC_MESSAGES/messages.po, i18n/locale/sk/LC_MESSAGES/messages.po
@katerinacharvatova souhlasila s odstraněním adresy, protože se jich vždy ptáme po soutěži explicitně. Doufám, že není nutná u českých týmů pro nějaké byrokratické účely.
=> Update fol11 form

data/emails/fyziklani/fyziklani2022/participant.cs.latte, data/emails/fyziklani/fyziklani2022/participant.en.latte, data/emails/fyziklani/fyziklani2022/teacher.cs.latte, data/emails/fyziklani/fyziklani2022/teacher.en.latte
přidání infa o platbách a detailu přihlášky do mailů
=> update payment info

data/emails/fyziklani/fyziklani2022/participant.cs.latte, data/emails/fyziklani/fyziklani2022/participant.en.latte, data/emails/fyziklani/fyziklani2022/teacher.cs.latte, data/emails/fyziklani/fyziklani2022/teacher.en.latte
změna rautu na rozbor úloh v registračních mailech
=> delete raut from mails

data/emails/fyziklani/fyziklani2022/payment/create.cs.latte
smazat zapomenuté info o specifickém symbolu v cz
=> update payment mails

app/config/payments/payment16.neon
přeposílání na fyziklani a ne jen mně
=> change bcc

app/Components/Forms/Rules/BornNumber.php
=> fix born_id control

app/Models/Submits/PDFStamper.php
Miško je na mobile a je lenivý zapínať PC :)
=> Fix pdfstamper

data/emails/sous/inc/urgent1.latte, data/emails/sous/inc/urgent2.latte, data/emails/sous/inc/urgent3.latte
=> delete form link

data/events/soustredeni/sous35j.neon
=> fix wrong param

app/Models/ORM/Models/EmailMessageModel.php, app/Models/ORM/Models/PersonModel.php, app/Modules/Core/PresenterTraits/ContestPresenterTrait.php, app/Modules/Core/PresenterTraits/YearPresenterTrait.php, app/Modules/CoreModule/DispatchPresenter.php, app/Modules/CoreModule/templates/Dispatch/default.latte, app/config/navigation.neon, app/css/mixins/navigation-item.scss, i18n/locale/cs/LC_MESSAGES/messages.po, tools/mailer.php
Dispatch screen treba prepísať!!!!
=> Fix Public presenter & fix mailer

app/Models/Authorization/Assertions/SelfAssertion.php
=> SelfAssertion fix

data/events/dsef/dsef28.neon, i18n/locale/cs/LC_MESSAGES/messages.po
remove accommodation from dsef application and fix translations
=> remove accommodation and fix translation

data/events/fyziklani/defaultFyziklani.neon, data/events/fyziklani/fyziklani17.neon
add fyziklani17 neon file and default neon
=> add FOF17 neon file

app/Components/EntityForms/Fyziklani/FOLTeamFormComponent.php, i18n/locale/cs/LC_MESSAGES/messages.po, i18n/locale/sk/LC_MESSAGES/messages.po
adding comments (describing family and other name) in application form
=> app. form - family and other name description

app/Models/ORM/Models/CountryModel.php
=> fix phone numbers

app/Models/ORM/Models/Fyziklani/GameSetupModel.php, data/events/dsef/dsef28.neon
=> add phone for next year

app/Models/ORM/Models/Schedule/PersonScheduleModel.php
=> edit schedule group label

app/Components/Controls/Person/Detail/OrgListComponent.php, app/Models/Authentication/AccountManager.php
=> Oprava odkazu na nastavení hesla pro nový účet

app/Models/ORM/Models/EventModel.php, app/Models/WebService/XMLHelper.php
xml eventu obsahuje všechny data co json.
=> Fix event xml
